services:

  frontend:
    build: 
      context: ./front
      dockerfile: ./front/Dockerfile
    ports:
      - 8083:80
    volumes:
      - ./front:/var/www/html/

  api:
    build:
      context: ./api 
      dockerfile: ./api/Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html/

  database:
    #image: mysql
    build:
      context: ./db_data 
      dockerfile: ./db_data/Dockerfile
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apiDev_db
      - MYSQL_USER=apiDev
      - MYSQL_PASSWORD=password

volumes:
  db-data: