version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 8083:80
    volumes:
      - ./front:/var/www/html/  # Monter le code source pour le rechargement à chaud
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8081:80
    #restart: on-failure
    volumes:
      - ./api:/var/www/html/ # Monter le code source pour le rechargement à chaud
    
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  database:
    build:
      context: .
      dockerfile: ./db_data/Dockerfile
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apiDev_db
      - MYSQL_USER=apiDev
      - MYSQL_PASSWORD=password
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  db-data: