# Pour le dev
services:
  frontend:
    build: 
      context: ./front
      dockerfile: Dockerfile
    image: pa-front:latest
    #image: spatulox/pa-front:latest
    volumes:
      - ./front:/var/www/html/
    ports:
      - 8083:80
    depends_on:
      - api

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: pa-api:latest
    #image: spatulox/pa-api:latest
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html/
    depends_on:
      - database

  ticket:
    image: spatulox/pa-ticket:latest
    ports:
      - 8085:8085
    environment:
      - DB_CONTAINER_NAME=database
    depends_on:
      - database


  database:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apiDev_db
      - MYSQL_USER=apiDev
      - MYSQL_PASSWORD=password

volumes:
  db-data:
