const dico = {
    "EN":{
        "update":"update ",
        "Update":"Update ",
        "succed":"succed ",
        "success":"success ",
        "failed":"failed ",
        "Failed":"Failed ",
        "delete":"delete ",
        "Delete":"Delete ",
        "deleted":"deleted ",
        "Delete":"Delete ",
        "user":"user ",
        "User":"User ",
        "see":"see ",
        "See":"See ",
        "planning":"planning ",
        "Planning":"Planning ",
        "retrieved":"retrieved ",
        "Retrieved":"Retrieved ",
        "all":"all ",
        "All":"All ",
        "impossible":"impossible ",
        "Impossible":"Impossible ",
        "to":"to ",
        "your":"your ",
        "Your":"Your ",
        "the":"the ",
        "The":"The ",
        "for":"for ",
        "For":"For ",
        "has been":"has been ",
        "validate":"validate ",
        "Validate":"Validate "

    },
    "FR":{
        "update":"mise à jour ",
        "Update":"Mise à jour ",
        "Success":"Succès ",
        "success":"succès ",
        "failed":"échoué ",
        "Failed":"Échoué ",
        "delete":"supprimé ",
        "Delete":"Supprimé ",
        "deleted":"supprimer ",
        "Delete":"Supprimé ",
        "user":"utilisateur ",
        "User":"Utilisateur ",
        "See":"Voir ",
        "see":"voir ",
        "planning":"planning ",
        "Planning":"Planning ",
        "retrieved":"récupéré ",
        "Retrieved":"Récupéré ",
        "all":"tous les ",
        "All":"Tous les ",
        "impossible":"impossible ",
        "Impossible":"Impossible ",
        "to":"de ",
        "your":"votre ",
        "Your":"Votre ",
        "the":"the ",
        "The":"The ",
        "for":"pour ",
        "For":"Pour ",
        "has been":"a été ",
        "validate":"validé ",
        "Validate":"Validé "
    }
}